lsi: false
safe: true

# Turn off smart quotes.
kramdown:
  smart_quotes: ["apos", "apos", "quot", "quot"]

plugins:
  - jekyll-redirect-from

defaults:
 -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
