markdown: CommonMarkGhPages
commonmark:
    options: ["UNSAFE", "FOOTNOTES"]
    extensions: ["strikethrough", "autolink", "table"]
plugins:
  - jekyll-redirect-from
  - jekyll-sitemap

permalink: /:title/

defaults:
    -
        scope:
            path: ""
        values:
            layout: default

url: https://weakish.github.io
title: mmap.page
repo: weakish/weakish.github.com

articles:
    - [dive-into/ruby.md, "Mon, 5 Sep 2022 12:07:30 +0000"]
    - [dive-into/gitmoji.md, "Mon, 5 Sep 2022 11:26:30 +0000"] 
    - [vim/spell.md, "Mon, 5 Sep 2022 08:51:52 +0000"] 
    - [vim/completion.md, "Mon, 5 Sep 2022 08:48:16 +0000"]
    - [dive-into/ts-check.md, "Mon, 15 Aug 2022 15:50:07 +0000"]
    - [dive-into/eslint.md, "Fri, 11 Jun 2021 10:13:23 +0800"]
    # - [dive-into/osx.md, "Mon, 15 Aug 2022 04:13:10 +0000"]
    # - [dive-into/i3.md, "Mon, 25 Jan 2021 23:47:13 +0800"]
    # - dive-into/android.md
    # - lists/vps.md
    # - dive-into/pyinfra.md
    # - dive-into/wireguard.md
    # - dive-into/borg.md
    - [dive-into/make.md, "Tue, 21 Jan 2020 21:35:48 +0800"]
    # - dive-into/npm.md
    - [dive-into/typescript.md, "Thu, 26 Dec 2019 23:30:44 +0800"]
    # - dive-into/react.md
    - [dive-into/rarcrack.md, "Sun, 24 Nov 2019 04:12:03 +0800"]
    # - dive-into/puppet.md
    # - dive-into/cyclejs.md
    - [dive-into/gh-pages.md, "Sat, 23 Nov 2019 17:09:04 +0800"]
    # - dive-into/jetbrains.md
    # - dive-into/go.md
    # - dive-into/rust.md
    # - dive-into/haskell.md
    # - dive-into/ocaml.md
    # - dive-into/flow.md
    - [dive-into/exceptions.md, "Thu, 6 Dec 2018 17:32:43 +0800"]
    # - dive-into/kotlin.md
    # - dive-into/ceylon-kotlin.md
    - [java/a-little.md, "Sun, 4 Nov 2018 23:45:29 +0800"]
    - [web/html-history.md, "Sun, 4 Nov 2018 23:45:29 +0800"]
    # - dive-into/base64.md
    # - dive-into/fish.md
    # - coding-style/
