services:
  - type: web
    name: weakish
    env: static
    buildCommand: curl -fsSL https://deno.land/x/install/install.sh | sh && /opt/render/.deno/bin/deno task build
    staticPublishPath: ./_site
    domains:
      - mmap.page
    headers:
      - path: /LICENSE
        name: Content-Type
        value: text/plain
    routes:
      - type: redirect
        source: /coding-style/javascript/
        destination: /dive-into/eslint/
      - type: redirect
        source: /coding-style/typescript/
        destination: /dive-into/eslint/
      - type: redirect
        source: /coding-style/:lang/
        destination: https://weakish.github.io/coding-style/:lang/
      - type: redirect
        source: /coding-style/
        destination: https://weakish.github.io/coding-style/
      - type: redirect
        source: /coding-style/*
        destination: https://weakish.github.io/coding-style/
      - type: rewrite
        source: /teapot
        destination: https://teapot.onrender.com
