var index = [
{'name': 'io.github.weakish.sysexits', 'type': 'package', 'url': 'index.html#section-package', 'doc': '<p>Maps sysexits.h to Ceylon exceptions, except <code>EX_OK</code>.</p>', 'tags': [],'icons': ['icon-package']},
{'name': 'CommandLineUsageError.exit_code', 'type': 'value', 'url': 'CommandLineUsageError.type.html#exit_code', 'doc': '<p>EX_USAGE</p>', 'tags': [],'icons': ['icon-shared-member']},
{'name': 'CommandLineUsageError', 'type': 'class', 'url': 'CommandLineUsageError.type.html', 'doc': '<p>Command line usage error, e.g. missing argument for option.</p>', 'tags': [],'icons': ['icon-class']},
{'name': 'DataFormatError.exit_code', 'type': 'value', 'url': 'DataFormatError.type.html#exit_code', 'doc': '<p>EX_DATAERR</p>', 'tags': [],'icons': ['icon-shared-member']},
{'name': 'DataFormatError', 'type': 'class', 'url': 'DataFormatError.type.html', 'doc': '<p>Data format error, e.g. passing a input file with wrong type.</p>', 'tags': [],'icons': ['icon-class']},
{'name': 'NoInputError.exit_code', 'type': 'value', 'url': 'NoInputError.type.html#exit_code', 'doc': '<p>EX_NOINPUT</p>', 'tags': [],'icons': ['icon-shared-member']},
{'name': 'NoInputError', 'type': 'class', 'url': 'NoInputError.type.html', 'doc': '<p>Cannot open input.</p>', 'tags': [],'icons': ['icon-class']},
{'name': 'NoUserError.exit_code', 'type': 'value', 'url': 'NoUserError.type.html#exit_code', 'doc': '<p>EX_NOUSER</p>', 'tags': [],'icons': ['icon-shared-member']},
{'name': 'NoUserError', 'type': 'class', 'url': 'NoUserError.type.html', 'doc': '<p>Addressee unknown.</p>', 'tags': [],'icons': ['icon-class']},
{'name': 'NoHostError.exit_code', 'type': 'value', 'url': 'NoHostError.type.html#exit_code', 'doc': '<p>EX_NOHOST</p>', 'tags': [],'icons': ['icon-shared-member']},
{'name': 'NoHostError', 'type': 'class', 'url': 'NoHostError.type.html', 'doc': '<p>Host name unknown.</p>', 'tags': [],'icons': ['icon-class']},
{'name': 'ServiceUnavailableError.exit_code', 'type': 'value', 'url': 'ServiceUnavailableError.type.html#exit_code', 'doc': '<p>EX_UNAVAILABLE</p>', 'tags': [],'icons': ['icon-shared-member']},
{'name': 'ServiceUnavailableError', 'type': 'class', 'url': 'ServiceUnavailableError.type.html', 'doc': '<p>Service unavailable.</p>', 'tags': [],'icons': ['icon-class']},
{'name': 'InternalSoftwareError.exit_code', 'type': 'value', 'url': 'InternalSoftwareError.type.html#exit_code', 'doc': '<p><code>ex_software</code> i.e. internal software error (sysexits.h)</p>', 'tags': [],'icons': ['icon-shared-member']},
{'name': 'InternalSoftwareError', 'type': 'class', 'url': 'InternalSoftwareError.type.html', 'doc': '<p>Internal software error.</p>', 'tags': [],'icons': ['icon-class']},
{'name': 'NotImplementedException', 'type': 'class', 'url': 'NotImplementedException.type.html', 'doc': '<p>Similar to UnsupportedOperationException in Java.</p>', 'tags': [],'icons': ['icon-class']},
{'name': 'NotImplementedYetException', 'type': 'class', 'url': 'NotImplementedYetException.type.html', 'doc': '<p>Features will be implemented in future.</p>', 'tags': [],'icons': ['icon-class']},
{'name': 'SystemError.exit_code', 'type': 'value', 'url': 'SystemError.type.html#exit_code', 'doc': '<p>EX_OSERR</p>', 'tags': [],'icons': ['icon-shared-member']},
{'name': 'SystemError', 'type': 'class', 'url': 'SystemError.type.html', 'doc': '<p>Low level system error, e.g. jvm and js runtime error or os error.</p>', 'tags': [],'icons': ['icon-class']},
{'name': 'OSFileError.exit_code', 'type': 'value', 'url': 'OSFileError.type.html#exit_code', 'doc': '<p>EX_OSFILE</p>', 'tags': [],'icons': ['icon-shared-member']},
{'name': 'OSFileError', 'type': 'class', 'url': 'OSFileError.type.html', 'doc': '<p>Critical OS file missing.</p>', 'tags': [],'icons': ['icon-class']},
{'name': 'CanNotCreateFileError.exit_code', 'type': 'value', 'url': 'CanNotCreateFileError.type.html#exit_code', 'doc': '<p>EX_CANTCREAT</p>', 'tags': [],'icons': ['icon-shared-member']},
{'name': 'CanNotCreateFileError', 'type': 'class', 'url': 'CanNotCreateFileError.type.html', 'doc': '<p>Can\'t create (user) output file.</p>', 'tags': [],'icons': ['icon-class']},
{'name': 'IOError.exit_code', 'type': 'value', 'url': 'IOError.type.html#exit_code', 'doc': '<p>EX_IOERR</p>', 'tags': [],'icons': ['icon-shared-member']},
{'name': 'IOError', 'type': 'class', 'url': 'IOError.type.html', 'doc': '<p>Input/output error.</p>', 'tags': [],'icons': ['icon-class']},
{'name': 'TempFailureError.exit_code', 'type': 'value', 'url': 'TempFailureError.type.html#exit_code', 'doc': '<p>EX_TEMPFAIL</p>', 'tags': [],'icons': ['icon-shared-member']},
{'name': 'TempFailureError', 'type': 'class', 'url': 'TempFailureError.type.html', 'doc': '<p>Temp failure; user is invited to retry.</p>', 'tags': [],'icons': ['icon-class']},
{'name': 'RemoteError.exit_code', 'type': 'value', 'url': 'RemoteError.type.html#exit_code', 'doc': '<p>EX_PROTOCOL</p>', 'tags': [],'icons': ['icon-shared-member']},
{'name': 'RemoteError', 'type': 'class', 'url': 'RemoteError.type.html', 'doc': '<p>Remote error.</p>', 'tags': [],'icons': ['icon-class']},
{'name': 'NoPermissionError.exit_code', 'type': 'value', 'url': 'NoPermissionError.type.html#exit_code', 'doc': '<p>EX_NOPERM</p>', 'tags': [],'icons': ['icon-shared-member']},
{'name': 'NoPermissionError', 'type': 'class', 'url': 'NoPermissionError.type.html', 'doc': '<p>permission denied.</p>', 'tags': [],'icons': ['icon-class']},
{'name': 'ConfigurationError.exit_code', 'type': 'value', 'url': 'ConfigurationError.type.html#exit_code', 'doc': '<p>EX_CONFIG</p>', 'tags': [],'icons': ['icon-shared-member']},
{'name': 'ConfigurationError', 'type': 'class', 'url': 'ConfigurationError.type.html', 'doc': '<p>Wrong configuration.</p>', 'tags': [],'icons': ['icon-class']},
{'name': 'io.github.weakish.sysexits', 'type': 'module', 'url': 'index.html', 'doc': '<p>Exceptions mapping <code>sysexits.h</code>.</p>', 'tags': [],'icons': ['icon-module']}];
var tagIndex = [
];
